# Generated by Django 4.2.7 on 2023-11-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[(1, 'Manager'), (2, 'Employee'), (3, 'Admin')], verbose_name='Тип пользователя'),
        ),
    ]
