# Generated by Django 4.2.7 on 2023-11-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20231108_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=23, max_length=255, verbose_name='Адрес сотрудника'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Junior'), (2, 'Middle'), (3, 'Senior')], default=1, verbose_name='Уровень сотрудника'),
            preserve_default=False,
        ),
    ]
