version: '3.9'
services:
    postgres:
        image: postgres:15.1
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: username
            POSTGRES_PASSWORD: postgresql_password
            POSTGRES_DB: database_name
            PGDATA: /var/lib/postgresql/data/dbfiles
        volumes:
            - ./DbData:/var/lib/postgresql/data
            - ./DbData:/docker-entrypoint-initdb.d/
        container_name: pgdb
