
GRANT ALL PRIVILEGES ON DATABASE database_name TO username;
CREATE SCHEMA IF NOT EXISTS public;



CREATE TABLE IF NOT EXISTS django_session (
	session_key varchar(40) NOT NULL,
	session_data text NOT NULL,
	expire_date timestamptz NOT NULL,
	CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);

CREATE TABLE IF NOT EXISTS "TaskType" (
	uuid uuid NOT NULL,
	"name" varchar(128) NOT NULL,
	priority int2 NOT NULL,
	work_time int2 NOT NULL,
	condition_1 varchar(256) NOT NULL,
	condition_2 varchar(256) NOT NULL,
	grade int2 NOT NULL,
	CONSTRAINT "TaskType_grade_check" CHECK ((grade >= 0)),
	CONSTRAINT "TaskType_pkey" PRIMARY KEY (uuid),
	CONSTRAINT "TaskType_priority_check" CHECK ((priority >= 0)),
	CONSTRAINT "TaskType_work_time_check" CHECK ((work_time >= 0))
);


CREATE TABLE IF NOT EXISTS django_migrations (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	app varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	applied timestamptz NOT NULL,
	CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "AgentPoint" (
	uuid uuid NOT NULL,
	address varchar(255) NOT NULL,
	agent_point_date varchar(25) NOT NULL,
	materials bool NOT NULL,
	last_card_given date NULL,
	num_given_cards int2 NOT NULL,
	approved_requests int2 NOT NULL,
	last_deliver date,
	last_teaching date,
	last_stimulation date,
	CONSTRAINT "AgentPoint_pkey" PRIMARY KEY (uuid)
);


CREATE TABLE IF NOT EXISTS auth_group (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	"name" varchar(150) NOT NULL,
	CONSTRAINT auth_group_name_key UNIQUE (name),
	CONSTRAINT auth_group_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS accounts_user (
	"password" varchar(128) NOT NULL,
	last_login timestamptz NULL,
	is_superuser bool NOT NULL,
	username varchar(150) NOT NULL,
	first_name varchar(150) NOT NULL,
	last_name varchar(150) NOT NULL,
	is_staff bool NOT NULL,
	is_active bool NOT NULL,
	date_joined timestamptz NOT NULL,
	uuid uuid NOT NULL,
	"role" int2 NOT NULL,
	phone_number varchar(32) NOT NULL,
	middle_name varchar(100) NOT NULL,
	email varchar(255) NOT NULL,
	grade int2 NOT NULL,
	address varchar(255) NOT NULL,
	CONSTRAINT accounts_user_email_key UNIQUE (email),
	CONSTRAINT accounts_user_grade_check CHECK ((grade >= 0)),
	CONSTRAINT accounts_user_pkey PRIMARY KEY (uuid),
	CONSTRAINT accounts_user_username_key UNIQUE (username)
);
CREATE TABLE IF NOT EXISTS django_content_type (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	app_label varchar(100) NOT NULL,
	model varchar(100) NOT NULL,
	CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model),
	CONSTRAINT django_content_type_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS auth_permission (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	"name" varchar(255) NOT NULL,
	content_type_id int4 NOT NULL,
	codename varchar(100) NOT NULL,
	CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename),
	CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
	CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED
);


CREATE TABLE IF NOT EXISTS accounts_user_user_permissions (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	user_id uuid NOT NULL,
	permission_id int4 NOT NULL,
	CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id),
	CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id),
	CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(uuid) DEFERRABLE INITIALLY DEFERRED
);




CREATE TABLE IF NOT EXISTS django_admin_log (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	action_time timestamptz NOT NULL,
	object_id text NULL,
	object_repr varchar(200) NOT NULL,
	action_flag int2 NOT NULL,
	change_message text NOT NULL,
	content_type_id int4 NULL,
	user_id uuid NOT NULL,
	CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0)),
	CONSTRAINT django_admin_log_pkey PRIMARY KEY (id),
	CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_user_uuid FOREIGN KEY (user_id) REFERENCES public.accounts_user(uuid) DEFERRABLE INITIALLY DEFERRED
);



CREATE TABLE IF NOT EXISTS authtoken_token (
	"key" varchar(40) NOT NULL,
	created timestamptz NOT NULL,
	user_id uuid NOT NULL,
	CONSTRAINT authtoken_token_pkey PRIMARY KEY (key),
	CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id),
	CONSTRAINT authtoken_token_user_id_35299eff_fk_accounts_user_uuid FOREIGN KEY (user_id) REFERENCES public.accounts_user(uuid) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE public."Task" (
	uuid uuid NOT NULL,
	appointment_date date NULL,
	priority int2 NOT NULL,
	status int2 NOT NULL,
	"comment" text NULL,
	favorite bool NOT NULL,
	agent_point_id uuid NOT NULL,
	employee_id uuid NULL,
	task_type_id uuid NOT NULL,
	CONSTRAINT "Task_pkey" PRIMARY KEY (uuid),
	CONSTRAINT "Task_priority_check" CHECK ((priority >= 0)),
	CONSTRAINT "Task_status_check" CHECK ((status >= 0)),
    CONSTRAINT "Task_agent_point_id_0ec27223_fk_AgentPoint_uuid" FOREIGN KEY (agent_point_id) REFERENCES public."AgentPoint"(uuid) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "Task_employee_id_493e2cab_fk_accounts_user_uuid" FOREIGN KEY (employee_id) REFERENCES public.accounts_user(uuid) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "Task_task_type_id_c8b3aac6_fk_TaskType_uuid" FOREIGN KEY (task_type_id) REFERENCES public."TaskType"(uuid) DEFERRABLE INITIALLY DEFERRED
);



CREATE TABLE IF NOT EXISTS accounts_user_groups (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	user_id uuid NOT NULL,
	group_id int4 NOT NULL,
	CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id),
	CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id),
	CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_uuid FOREIGN KEY (user_id) REFERENCES public.accounts_user(uuid) DEFERRABLE INITIALLY DEFERRED
);


CREATE TABLE IF NOT EXISTS auth_group_permissions (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	group_id int4 NOT NULL,
	permission_id int4 NOT NULL,
	CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id),
	CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
	CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX "Task_agent_point_id_0ec27223" ON public."Task" USING btree (agent_point_id);
CREATE INDEX "Task_employee_id_493e2cab" ON public."Task" USING btree (employee_id);
CREATE INDEX "Task_task_type_id_c8b3aac6" ON public."Task" USING btree (task_type_id);
CREATE INDEX accounts_user_email_b2644a56_like ON public.accounts_user USING btree (email varchar_pattern_ops);
CREATE INDEX accounts_user_username_6088629e_like ON public.accounts_user USING btree (username varchar_pattern_ops);
CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);
CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);
CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.accounts_user_groups USING btree (group_id);
CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.accounts_user_groups USING btree (user_id);
CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);
CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);
CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.accounts_user_user_permissions USING btree (permission_id);
CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.accounts_user_user_permissions USING btree (user_id);
CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);
CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);
CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);
CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);
CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


ALTER TABLE public."AgentPoint" ADD COLUMN IF NOT EXISTS materials bool NOT NULL;
ALTER TABLE public."TaskType" ADD COLUMN IF NOT EXISTS condition_2 varchar(256) NOT NULL;
ALTER TABLE public."TaskType" ADD COLUMN IF NOT EXISTS grade int2 NOT NULL;
ALTER TABLE public.accounts_user ADD COLUMN IF NOT EXISTS address varchar(255) NOT NULL;
ALTER TABLE public.accounts_user ADD COLUMN IF NOT EXISTS "role" int2 NOT NULL;
ALTER TABLE public.django_admin_log ADD COLUMN IF NOT EXISTS change_message text NOT NULL;
ALTER TABLE public.django_migrations ADD COLUMN IF NOT EXISTS app varchar(255) NOT NULL;
ALTER TABLE public.authtoken_token ADD COLUMN IF NOT EXISTS user_id uuid NOT NULL;
ALTER TABLE public.django_admin_log ADD COLUMN IF NOT EXISTS object_repr varchar(200) NOT NULL;
ALTER TABLE public.django_admin_log ADD  COLUMN IF NOT EXISTS user_id uuid NOT NULL;
ALTER TABLE public.accounts_user_groups ADD COLUMN IF NOT EXISTS user_id uuid NOT NULL;
ALTER TABLE public.django_migrations ADD COLUMN IF NOT EXISTS applied timestamptz NOT NULL;
ALTER TABLE public."AgentPoint" ADD COLUMN IF NOT EXISTS approved_requests int2 NOT NULL;
ALTER TABLE public.accounts_user ADD COLUMN IF NOT EXISTS grade int2 NOT NULL;
ALTER TABLE public.accounts_user_groups ADD COLUMN IF NOT EXISTS id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE);
ALTER TABLE public.accounts_user ADD COLUMN IF NOT EXISTS is_active bool NOT NULL;
ALTER TABLE public.accounts_user ADD COLUMN IF NOT EXISTS is_superuser bool NOT NULL;
ALTER TABLE public.django_admin_log ADD COLUMN IF NOT EXISTS content_type_id int4 NULL;
ALTER TABLE public."AgentPoint" ADD COLUMN IF NOT EXISTS uuid uuid NOT NULL;
ALTER TABLE public."TaskType" ADD COLUMN IF NOT EXISTS "name" varchar(128) NOT NULL;
ALTER TABLE public.accounts_user ADD COLUMN IF NOT EXISTS last_name varchar(150) NOT NULL;
ALTER TABLE public."AgentPoint" ADD COLUMN IF NOT EXISTS agent_point_date varchar(25) NOT NULL;
ALTER TABLE public.accounts_user ADD COLUMN IF NOT EXISTS username varchar(150) NOT NULL;
ALTER TABLE public.django_content_type ADD COLUMN IF NOT EXISTS model varchar(100) NOT NULL;
ALTER TABLE public."AgentPoint" ADD COLUMN IF NOT EXISTS last_deliver date NOT NULL;
ALTER TABLE public."TaskType" ADD COLUMN IF NOT EXISTS priority int2 NOT NULL;
ALTER TABLE public."AgentPoint" ADD COLUMN IF NOT EXISTS num_given_cards int2 NOT NULL;
ALTER TABLE public."TaskType" ADD COLUMN IF NOT EXISTS work_time int2 NOT NULL;
ALTER TABLE public.django_admin_log ADD COLUMN IF NOT EXISTS action_flag int2 NOT NULL;
ALTER TABLE public."TaskType" ADD COLUMN IF NOT EXISTS condition_1 varchar(256) NOT NULL;
ALTER TABLE public.accounts_user ADD COLUMN IF NOT EXISTS email varchar(255) NOT NULL;
ALTER TABLE public.auth_permission ADD COLUMN IF NOT EXISTS "name" varchar(255) NOT NULL;
ALTER TABLE public.accounts_user ADD COLUMN IF NOT EXISTS date_joined timestamptz NOT NULL;
ALTER TABLE public.accounts_user_user_permissions ADD COLUMN IF NOT EXISTS id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE);
ALTER TABLE public.django_content_type ADD COLUMN IF NOT EXISTS app_label varchar(100) NOT NULL;
ALTER TABLE public."AgentPoint" ADD COLUMN IF NOT EXISTS address varchar(255) NOT NULL;
ALTER TABLE public.django_session ADD COLUMN IF NOT EXISTS session_key varchar(40) NOT NULL;
ALTER TABLE public."Task" ADD COLUMN IF NOT EXISTS "comment" text NULL;
ALTER TABLE public."AgentPoint" ADD COLUMN IF NOT EXISTS last_stimulation date NOT NULL;
ALTER TABLE public.auth_group_permissions ADD COLUMN IF NOT EXISTS permission_id int4 NOT NULL;
ALTER TABLE public.django_admin_log ADD COLUMN IF NOT EXISTS id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE);
ALTER TABLE public.auth_permission ADD COLUMN IF NOT EXISTS content_type_id int4 NOT NULL;
ALTER TABLE public.django_admin_log ADD COLUMN IF NOT EXISTS action_time timestamptz NOT NULL;
ALTER TABLE public."AgentPoint" ADD COLUMN IF NOT EXISTS last_teaching date NOT NULL;
ALTER TABLE public."Task" ADD COLUMN IF NOT EXISTS priority int2 NOT NULL;
ALTER TABLE public.authtoken_token ADD COLUMN IF NOT EXISTS "key" varchar(40) NOT NULL;
ALTER TABLE public.auth_group_permissions ADD COLUMN IF NOT EXISTS group_id int4 NOT NULL;
ALTER TABLE public.accounts_user ADD COLUMN IF NOT EXISTS last_login timestamptz NULL;
ALTER TABLE public.auth_group ADD COLUMN IF NOT EXISTS "name" varchar(150) NOT NULL;
ALTER TABLE public.accounts_user ADD COLUMN IF NOT EXISTS "password" varchar(128) NOT NULL;
ALTER TABLE public.accounts_user ADD COLUMN IF NOT EXISTS first_name varchar(150) NOT NULL;
ALTER TABLE public.accounts_user_user_permissions ADD COLUMN IF NOT EXISTS user_id uuid NOT NULL;
ALTER TABLE public.accounts_user ADD COLUMN IF NOT EXISTS phone_number varchar(32) NOT NULL;
ALTER TABLE public."TaskType" ADD COLUMN IF NOT EXISTS uuid uuid NOT NULL;
ALTER TABLE public."Task" ADD COLUMN IF NOT EXISTS favorite bool NOT NULL;
ALTER TABLE public.accounts_user_user_permissions ADD COLUMN IF NOT EXISTS permission_id int4 NOT NULL;
ALTER TABLE public.auth_group ADD COLUMN IF NOT EXISTS id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE);
ALTER TABLE public.django_migrations ADD COLUMN IF NOT EXISTS "name" varchar(255) NOT NULL;
ALTER TABLE public."Task" ADD COLUMN IF NOT EXISTS appointment_date date NULL;
ALTER TABLE public.django_session ADD COLUMN IF NOT EXISTS expire_date timestamptz NOT NULL;
ALTER TABLE public."Task" ADD COLUMN IF NOT EXISTS status int2 NOT NULL;
ALTER TABLE public."Task" ADD COLUMN IF NOT EXISTS uuid uuid NOT NULL;
ALTER TABLE public."Task" ADD COLUMN IF NOT EXISTS employee_id uuid NULL;
ALTER TABLE public.accounts_user ADD COLUMN IF NOT EXISTS middle_name varchar(100) NOT NULL;
ALTER TABLE public."AgentPoint" ADD COLUMN IF NOT EXISTS last_card_given date NULL;
ALTER TABLE public.authtoken_token ADD COLUMN IF NOT EXISTS created timestamptz NOT NULL;
ALTER TABLE public.accounts_user ADD COLUMN IF NOT EXISTS uuid uuid NOT NULL;
ALTER TABLE public.django_admin_log ADD COLUMN IF NOT EXISTS object_id text NULL;
ALTER TABLE public.accounts_user_groups ADD COLUMN IF NOT EXISTS group_id int4 NOT NULL;
ALTER TABLE public.django_session ADD COLUMN IF NOT EXISTS session_data text NOT NULL;
ALTER TABLE public.auth_permission ADD COLUMN IF NOT EXISTS id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE);
ALTER TABLE public.accounts_user ADD COLUMN IF NOT EXISTS is_staff bool NOT NULL;
ALTER TABLE public.auth_permission ADD COLUMN IF NOT EXISTS codename varchar(100) NOT NULL;
ALTER TABLE public.django_content_type ADD COLUMN IF NOT EXISTS id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE);
ALTER TABLE public.django_migrations ADD COLUMN IF NOT EXISTS id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE);
ALTER TABLE public.auth_group_permissions ADD COLUMN IF NOT EXISTS id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE);


INSERT INTO public.accounts_user ("password", last_login, is_superuser, username, first_name, last_name, is_staff, is_active, date_joined, uuid, "role", phone_number, middle_name, email, grade, address) VALUES('pbkdf2_sha256$600000$byV4D5N3rdJpCzoZZaxIjx$dlLzeqP53U8Oq5dosqBNqfer+9D6ywgyV/mw/hk6I/M=', NULL, false, 'deryagin', 'Никита', 'Дерягин', false, true, '2023-11-09 14:36:25.236', '2e253b9a-7fbf-4ef3-bd89-b06de084aa8f'::uuid, 2, '', 'Владимирович', 'nikita@mail.ru', 3, 'Краснодар, Красная, д. 139');
INSERT INTO public.accounts_user ("password", last_login, is_superuser, username, first_name, last_name, is_staff, is_active, date_joined, uuid, "role", phone_number, middle_name, email, grade, address) VALUES('pbkdf2_sha256$600000$byV4D5N3rdJpCzoZZaxIjx$dlLzeqP53U8Oq5dosqBNqfer+9D6ywgyV/mw/hk6I/M=', NULL, false, 'petroshev', 'Валерий', 'Петрошев', false, true, '2023-11-09 14:37:55.783', 'da05c4a9-8e6f-43dc-a3b2-6cfd9ab75cda'::uuid, 2, '', 'Павлович', 'valeriy@mail.ru', 2, 'Краснодар, Красная, д. 139');
INSERT INTO public.accounts_user ("password", last_login, is_superuser, username, first_name, last_name, is_staff, is_active, date_joined, uuid, "role", phone_number, middle_name, email, grade, address) VALUES('pbkdf2_sha256$600000$byV4D5N3rdJpCzoZZaxIjx$dlLzeqP53U8Oq5dosqBNqfer+9D6ywgyV/mw/hk6I/M=', NULL, false, 'david', 'Давид', 'Евдокимов', false, true, '2023-11-09 14:38:35.077', '20275432-2740-4b4c-abf8-ecc909ca97ea'::uuid, 2, '', 'Тихонович', 'david@mail.ru', 1, 'Краснодар, Красная, д. 139');
INSERT INTO public.accounts_user ("password", last_login, is_superuser, username, first_name, last_name, is_staff, is_active, date_joined, uuid, "role", phone_number, middle_name, email, grade, address) VALUES('pbkdf2_sha256$600000$byV4D5N3rdJpCzoZZaxIjx$dlLzeqP53U8Oq5dosqBNqfer+9D6ywgyV/mw/hk6I/M=', NULL, false, 'adam', 'Адам', 'Иванов', false, true, '2023-11-09 14:39:44.525', '2c642334-91ed-42cb-a4fa-590ff930f658'::uuid, 2, '', 'Федорович', 'adam@mail.ru', 2, 'Краснодар, В.Н. Мачуги, 41');
INSERT INTO public.accounts_user ("password", last_login, is_superuser, username, first_name, last_name, is_staff, is_active, date_joined, uuid, "role", phone_number, middle_name, email, grade, address) VALUES('pbkdf2_sha256$600000$byV4D5N3rdJpCzoZZaxIjx$dlLzeqP53U8Oq5dosqBNqfer+9D6ywgyV/mw/hk6I/M=', NULL, false, 'ippolit', 'Ипполит', 'Бобылёв', false, true, '2023-11-09 14:40:10.132', 'd2cb0a29-38b3-462b-a097-684157af2b61'::uuid, 2, '', 'Альбертович', 'ippolit@mail.ru', 1, 'Краснодар, В.Н. Мачуги, 41');
INSERT INTO public.accounts_user ("password", last_login, is_superuser, username, first_name, last_name, is_staff, is_active, date_joined, uuid, "role", phone_number, middle_name, email, grade, address) VALUES('pbkdf2_sha256$600000$byV4D5N3rdJpCzoZZaxIjx$dlLzeqP53U8Oq5dosqBNqfer+9D6ywgyV/mw/hk6I/M=', NULL, false, 'v', 'Евгения', 'Беляева', false, true, '2023-11-09 14:40:39.939', '9305e0a7-15ba-4f44-85be-c3d2d15eacf5'::uuid, 2, '', 'Антоновна', 'evgeniya@mail.ru', 2, 'Краснодар, Красных Партизан, 321');
INSERT INTO public.accounts_user ("password", last_login, is_superuser, username, first_name, last_name, is_staff, is_active, date_joined, uuid, "role", phone_number, middle_name, email, grade, address) VALUES('pbkdf2_sha256$600000$byV4D5N3rdJpCzoZZaxIjx$dlLzeqP53U8Oq5dosqBNqfer+9D6ywgyV/mw/hk6I/M=', NULL, false, 'azariy', 'Азарий', 'Николаев', false, true, '2023-11-09 14:41:07.502', 'cfdaef5a-9d4d-4577-a931-31a9b1d21ae7'::uuid, 2, '', 'Платонович', 'azariy@mail.ru', 1, 'Краснодар, Красных Партизан, 321');
INSERT INTO public.accounts_user ("password", last_login, is_superuser, username, first_name, last_name, is_staff, is_active, date_joined, uuid, "role", phone_number, middle_name, email, grade, address) VALUES('pbkdf2_sha256$600000$byV4D5N3rdJpCzoZZaxIjx$dlLzeqP53U8Oq5dosqBNqfer+9D6ywgyV/mw/hk6I/M=', NULL, false, 'godlik', 'Эдуард', 'Галиханов', false, true, '2023-11-09 16:21:59.005', 'f7e5a2dd-359b-4cbe-b396-186cff129fa7'::uuid, 1, '', 'Радикович', 'galedra@mail.ru', 1, 'ул Дагестанская 15/1');
INSERT INTO public.accounts_user ("password", last_login, is_superuser, username, first_name, last_name, is_staff, is_active, date_joined, uuid, "role", phone_number, middle_name, email, grade, address) VALUES('pbkdf2_sha256$600000$byV4D5N3rdJpCzoZZaxIjx$dlLzeqP53U8Oq5dosqBNqfer+9D6ywgyV/mw/hk6I/M=', NULL, false, 'godlik1', 'Эдуард', 'Галиханов', false, true, '2023-11-09 17:28:58.339', '81c3f9c0-a014-4c7f-b0b3-603fe245d3d7'::uuid, 1, '', 'Радикович', 'galedra1@mail.ru', 1, 'ул Правды 18');

INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('015c1db9-dd43-472c-9781-0d23abca10ff'::uuid, 'ул. Ставропольская, д. 140', 'вчера', False, '2023-11-10', 0, 0, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('ae66976b-a3c8-4d99-9476-c8b2378558fd'::uuid, 'ул. им. Максима Горького, д. 128', 'давно', true, '2023-11-07', 3, 15, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('42487a8b-8793-4811-b6c3-5f2fa24d3580'::uuid, 'ул. им. Дзержинского, д. 100', 'давно', true, '2023-11-07', 1, 9, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('b0bcbb95-4ecf-4303-969b-881640ac1255'::uuid, 'ул. Красноармейская, д. 126', 'давно', true, '2023-11-10', 23, 38, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('7ba1e6d3-8023-45a3-b2c5-69f66c42ff1c'::uuid, 'х. Ленина, п/о. 37', 'давно', false, '2023-11-10', 0, 14, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('9f53209b-8517-4575-a08d-f11789b0da9a'::uuid, 'тер. Пашковский жилой массив, ул. Крылатая, д. 2', 'давно', true, '2023-10-30', 1, 19, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('d2ae9c8d-c5ec-4a14-8784-bb9379462a74'::uuid, 'ул. Восточно-Кругликовская, д. 64/2', 'давно', true, '2023-10-13', 12, 19, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('8fa5fe99-a7c4-45bd-902e-f9f6fe1d350f'::uuid, 'ул. Красных Партизан, д. 439', 'давно', true, '2023-10-08', 63, 84, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('e68c75cc-878e-4280-be63-459c31446bf1'::uuid, 'ул. Таманская, д. 153 к. 3, кв. 2', 'давно', true, '2023-11-09', 1, 15, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('6cd58873-0ee7-4eb8-a1ed-739af2277c92'::uuid, 'ул. им. Дзержинского, д. 165', 'давно', true, '2023-11-10', 0, 19, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('601a47e0-197d-4396-b0f9-9b9d6cca933c'::uuid, 'ст-ца. Елизаветинская, ул. Широкая, д. 260', 'давно', true, '2023-10-25', 15, 29, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('2ad3ac56-b160-4491-b96b-eabc76dc0466'::uuid, 'ул. им. Тургенева, д. 174, 1 этаж', 'давно', true, '2023-10-25', 15, 29, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('59dd49a2-72ad-450e-8efe-0218175b0fcc'::uuid, 'ул. Уральская, д. 162', 'давно', true, '2023-11-06', 5, 21, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('b0e2e4dc-18d7-48d9-84cd-97b6f36df119'::uuid, 'ул. Уральская, д. 79/1', 'вчера', false, '2023-11-10', 0, 5, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('03d7062d-c77b-4f18-88a3-5de14bad643b'::uuid, 'ул. им. Селезнева, д. 197/5', 'давно', true, '2023-11-03', 3, 14, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('67382cf4-13bf-4325-b569-d44c31b86307'::uuid, 'ул. Уральская, д. 117', 'вчера', false, '2023-11-10', 0, 0, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('757bd381-b9b6-40af-8eb5-84dd436ed2b3'::uuid, 'ул. им. 40-летия Победы, д. 20/1', 'давно', true, '2023-11-06', 15, 35, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('5ed5ae53-1c3a-435e-b7cb-e1feab9eb29f'::uuid, 'ул. им. Атарбекова, д. 24', 'вчера', false, '2023-11-10', 0, 6, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('6e8a6808-1bae-4c83-85d1-645ebe5ba993'::uuid, 'ул. им. Героя Аверкиева А.А., д. 8', 'давно', true, '2023-11-04', 6, 18, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('3b6dc150-3a64-410f-8223-f91382c4bfa7'::uuid, 'ул. им. Героя Аверкиева А.А., д. 8/1 к. мая, кв. 268', 'давно', true, '2023-11-10', 5, 15, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('e31fdeb5-260e-4687-847e-4c4d448ddf2b'::uuid, 'ул. им. Тургенева, д. 106', 'давно', true, '2023-11-08', 20, 96, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('35caffc7-422a-479d-a394-e07ca81951b8'::uuid, 'ул. Красных Партизан, д. 117', 'вчера', false, '2023-11-10', 0, 0, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('459b9a31-8448-47c3-99c4-3186cd6bd4d9'::uuid, 'ул. Северная, д. 389', 'давно', true, '2023-11-10', 0, 16, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('2bdbc6c3-082b-4851-bf0b-5e1524fe7e9c'::uuid, 'ул. Уральская, д. 166/3', 'давно', true, '2023-11-07', 29, 43, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('dc613b28-7998-44eb-b555-a73135765316'::uuid, 'ул. Северная, д. 524', 'давно', true, '2023-11-07', 4, 13, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('c68e929e-4d6a-4b0e-9786-30633f32808c'::uuid, 'ул. им. Кирилла Россинского, д. 61/1', 'давно', true, '2023-11-04', 5, 19, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('18cf4737-231d-40e8-b730-f1b4cc706322'::uuid, 'ул. Коммунаров, д. 258', 'давно', true, '2023-10-24', 30, 45, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('db165aaf-7f62-42a6-b60b-fa6030506e1e'::uuid, 'ул. им. Дзержинского, д. 100', 'давно', true, '2023-11-09', 4, 19, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('abd72c0f-467d-4d38-a7f2-94ca01a7782a'::uuid, 'ул. Северная, д. 326', 'давно', true, '2023-11-07', 9, 20, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('1b108aff-c60c-4899-bd21-35cc15341196'::uuid, 'ул. им. 40-летия Победы, д. 34', 'давно', false, '2023-11-10', 0, 19, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('b0ebac73-f655-402d-9576-d1028a6d410f'::uuid, 'ул. Красная, д. 176', 'давно', true, '2023-08-24', 72, 82, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('55232394-0247-4de9-8b14-22bd58a3d8d1'::uuid, 'ул. Уральская, д. 79/1', 'давно', true, '2023-10-17', 21, 32, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('d9080fb2-7d84-488d-a8cd-c354f914b63c'::uuid, 'ул. Северная, д. 326', 'давно', true, '2023-11-07', 4, 19, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('91c0cc4d-fd37-444e-a34a-2cc971cd3b54'::uuid, 'ул. Красная, д. 149', 'давно', true, '2023-11-01', 7, 10, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('89d7427f-67cc-4d89-a8fe-b2f649721743'::uuid, 'п. Березовый, ул. Целиноградская, д. 6/1', 'вчера', false, '2023-11-10', 0, 13, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('1bc47b48-6b3b-4f4d-9444-d76fa4398c4d'::uuid, 'ул. им. Дзержинского, д. 100', 'вчера', false, '2023-11-10', 0, 10, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('522b1eef-f6cc-4f01-8379-c587772dbf22'::uuid, 'ул. Российская, д. 418', 'давно', true, '2023-11-04', 14, 30, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('e4f43b7e-b3af-4cb3-9b83-96c6a4f7f476'::uuid, 'ул. им. Володи Головатого, д. 313', 'давно', true, '2023-11-04', 12, 65, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('ba5905a2-f985-4a18-b22e-61f2282b23b4'::uuid, 'ул. Красная, д. 145', 'давно', true, '2023-11-07', 4, 20, NULL, NULL, NULL);
INSERT INTO public."AgentPoint" (uuid, address, agent_point_date, materials, last_card_given, num_given_cards, approved_requests, last_deliver, last_teaching, last_stimulation) VALUES('45a41a6d-260a-43ed-beab-605698d506ed'::uuid, 'ул. Красная, д. 154', 'вчера', false, '2023-11-10', 0, 0, NULL, NULL, NULL);


INSERT INTO public."TaskType" (uuid, "name", priority, work_time, condition_1, condition_2, grade) VALUES('91f3bf5a-11e2-4963-99b1-e87b9cb1d14c'::uuid, 'Выезд на точку для стимулирования выдач', 1, 4, 'Дата выдачи последней карты более 7 дней назад, при этом есть одобренные заявки', ' ', 3);
INSERT INTO public."TaskType" (uuid, "name", priority, work_time, condition_1, condition_2, grade) VALUES('427c8c88-dc7e-4e89-9ad5-e5d2304e88ae'::uuid, 'Обучение агента', 2, 2, 'Отношение кол-ва выданных карт к одобренным заявкам менее 50%, если выдано больше 0 карт', ' ', 2);
INSERT INTO public."TaskType" (uuid, "name", priority, work_time, condition_1, condition_2, grade) VALUES('2d1a9f3f-8093-4e68-b2b9-3889621a2831'::uuid, 'Доставка карт и материалов', 3, 1, 'Точка подключена вчера', 'Карты и материалы не доставлялись', 1);


INSERT INTO public."Task" (uuid, appointment_date, priority, status, "comment", favorite, agent_point_id, employee_id, task_type_id) VALUES('a18e22ae-63c2-45f2-927d-602cd78f7083'::uuid, NULL, 1, 1, NULL, false, '45a41a6d-260a-43ed-beab-605698d506ed'::uuid, NULL, '427c8c88-dc7e-4e89-9ad5-e5d2304e88ae'::uuid);
INSERT INTO public."Task" (uuid, appointment_date, priority, status, "comment", favorite, agent_point_id, employee_id, task_type_id) VALUES('c80d97bc-09a0-414b-ad57-50893f4f4060'::uuid, NULL, 1, 1, NULL, false, '45a41a6d-260a-43ed-beab-605698d506ed'::uuid, NULL, '427c8c88-dc7e-4e89-9ad5-e5d2304e88ae'::uuid);
INSERT INTO public."Task" (uuid, appointment_date, priority, status, "comment", favorite, agent_point_id, employee_id, task_type_id) VALUES('abd58e14-3aaf-447f-970b-4b5133b4bb2d'::uuid, NULL, 1, 1, NULL, false, '45a41a6d-260a-43ed-beab-605698d506ed'::uuid, NULL, '427c8c88-dc7e-4e89-9ad5-e5d2304e88ae'::uuid);
INSERT INTO public."Task" (uuid, appointment_date, priority, status, "comment", favorite, agent_point_id, employee_id, task_type_id) VALUES('c2d620cd-3ecb-4068-a85c-668571223ac6'::uuid, NULL, 1, 1, NULL, false, '45a41a6d-260a-43ed-beab-605698d506ed'::uuid, NULL, '427c8c88-dc7e-4e89-9ad5-e5d2304e88ae'::uuid);
INSERT INTO public."Task" (uuid, appointment_date, priority, status, "comment", favorite, agent_point_id, employee_id, task_type_id) VALUES('6ab21a67-b9c9-4ec6-89c2-f6c3105c16a4'::uuid, NULL, 1, 1, NULL, false, '45a41a6d-260a-43ed-beab-605698d506ed'::uuid, NULL, '427c8c88-dc7e-4e89-9ad5-e5d2304e88ae'::uuid);
INSERT INTO public."Task" (uuid, appointment_date, priority, status, "comment", favorite, agent_point_id, employee_id, task_type_id) VALUES('59881329-a01e-44ec-8e85-55fa81e3d539'::uuid, NULL, 1, 1, NULL, false, '45a41a6d-260a-43ed-beab-605698d506ed'::uuid, NULL, '427c8c88-dc7e-4e89-9ad5-e5d2304e88ae'::uuid);
INSERT INTO public."Task" (uuid, appointment_date, priority, status, "comment", favorite, agent_point_id, employee_id, task_type_id) VALUES('e9d4d6ce-65c5-4ff0-978b-7fbada42b120'::uuid, NULL, 1, 1, NULL, false, '45a41a6d-260a-43ed-beab-605698d506ed'::uuid, NULL, '427c8c88-dc7e-4e89-9ad5-e5d2304e88ae'::uuid);
INSERT INTO public."Task" (uuid, appointment_date, priority, status, "comment", favorite, agent_point_id, employee_id, task_type_id) VALUES('70bde16e-b696-4d68-a532-1eee10a05c65'::uuid, NULL, 1, 1, NULL, false, '45a41a6d-260a-43ed-beab-605698d506ed'::uuid, NULL, '427c8c88-dc7e-4e89-9ad5-e5d2304e88ae'::uuid);
INSERT INTO public."Task" (uuid, appointment_date, priority, status, "comment", favorite, agent_point_id, employee_id, task_type_id) VALUES('7b77c625-6278-4116-89c9-83c658f02059'::uuid, NULL, 1, 1, NULL, false, '45a41a6d-260a-43ed-beab-605698d506ed'::uuid, NULL, '427c8c88-dc7e-4e89-9ad5-e5d2304e88ae'::uuid);






