# Generated by Django 4.2.7 on 2023-11-05 19:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('agent_point_date', models.CharField(max_length=50, verbose_name='Дата подключения точки')),
                ('materials', models.BooleanField(verbose_name='Материалы доставлены')),
                ('last_card_given', models.SmallIntegerField(verbose_name='Дата последней выдачи карты')),
                ('num_given_cards', models.SmallIntegerField(verbose_name='Выданные карты')),
                ('approved_requests', models.SmallIntegerField(verbose_name='Одобренные заявки')),
                ('employee', models.BigIntegerField(verbose_name='Исполнитель задания')),
                ('priority', models.SmallIntegerField(verbose_name='Приоритет')),
                ('address', models.CharField(default='Dagestanskaya', max_length=255, verbose_name='Адрес')),
                ('work_time', models.SmallIntegerField(verbose_name='Время на выполнение')),
                ('appointment_date', models.DateField(null=True, verbose_name='Время начала задачи')),
                ('status', models.SmallIntegerField(default=1, verbose_name='Статус задачи')),
                ('task_type', models.CharField(max_length=50, verbose_name='Тип задачи')),
            ],
            options={
                'verbose_name': 'Задачи',
                'permissions': ([('create_task', 'Can create task'), ('close_task', 'Can close task')],),
            },
        ),
    ]
