# Generated by Django 4.2.7 on 2023-11-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('uuid', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('uuid', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('agent_point_date', models.CharField(max_length=50, verbose_name='Дата подключения точки')),
                ('materials', models.BooleanField(verbose_name='Материалы доставлены')),
                ('last_card_given', models.SmallIntegerField(verbose_name='Дата последней выдачи карты')),
                ('num_given_cards', models.SmallIntegerField(verbose_name='Выданные карты')),
                ('approved_requests', models.SmallIntegerField(verbose_name='Одобренные заявки')),
                ('employee', models.BigIntegerField(verbose_name='Исполнитель задания')),
                ('priority', models.SmallIntegerField(verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Задачи',
            },
        ),
    ]
