# Generated by Django 4.2.7 on 2023-11-05 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': ([('create_task', 'Can create task'), ('close_task', 'Can close task')],), 'verbose_name': 'Задачи'},
        ),
    ]
