# Generated by Django 4.2.7 on 2023-11-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='agent_point_date',
            field=models.CharField(default='Недавно', max_length=50, verbose_name='Дата подключения точки'),
        ),
        migrations.AlterField(
            model_name='task',
            name='appointment_date',
            field=models.DateField(default='01-06-2003', null=True, verbose_name='Время начала задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='approved_requests',
            field=models.SmallIntegerField(default=10, verbose_name='Одобренные заявки'),
        ),
        migrations.AlterField(
            model_name='task',
            name='employee',
            field=models.BigIntegerField(null=True, verbose_name='Исполнитель задания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_card_given',
            field=models.DateField(default='01-06-2003', verbose_name='Дата последней выдачи карты'),
        ),
        migrations.AlterField(
            model_name='task',
            name='materials',
            field=models.BooleanField(default=True, verbose_name='Материалы доставлены'),
        ),
        migrations.AlterField(
            model_name='task',
            name='num_given_cards',
            field=models.SmallIntegerField(default=8, verbose_name='Выданные карты'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.SmallIntegerField(null=True, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(default=1, null=True, verbose_name='Статус задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(default='Забрать карта', max_length=50, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='work_time',
            field=models.SmallIntegerField(default=2, verbose_name='Время на выполнение'),
        ),
    ]
