# Generated by Django 4.2.7 on 2023-11-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_delete_employee_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='address',
            field=models.CharField(default='Dagestanskaya', max_length=255, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='task',
            name='appointment_date',
            field=models.DateTimeField(default=None, verbose_name='Время полей'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(default=0, verbose_name='Статус задачи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(default=None, max_length=50, verbose_name='Тип задачи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='work_time',
            field=models.SmallIntegerField(default=None, verbose_name='Время на выполнение'),
            preserve_default=False,
        ),
    ]
