# Generated by Django 4.2.7 on 2023-11-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_alter_task_agent_point_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='appointment_date',
            field=models.DateField(default='2000-01-01', null=True, verbose_name='Время начала задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_card_given',
            field=models.DateField(default='2000-01-01', verbose_name='Дата последней выдачи карты'),
        ),
    ]
