# Generated by Django 4.2.7 on 2023-11-08 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('appointment_date', models.DateField(null=True, verbose_name='Время начала задачи')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], verbose_name='Приоритет')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Appointed'), (2, 'On The Way'), (3, 'In Work'), (4, 'Finish')], default=1, verbose_name='Статус задачи')),
                ('task_type', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], verbose_name='Тип задачи')),
                ('comment', models.TextField(null=True, verbose_name='Коментарий к задаче')),
                ('favorite', models.BooleanField(default=False, verbose_name='Избранное?')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_task', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задачи',
                'db_table': 'Task',
            },
        ),
    ]
