# Generated by Django 4.2.7 on 2023-11-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Appointed'), (2, 'On The Way'), (3, 'In Work'), (4, 'Finish'), (5, 'Not Done'), (6, 'Tomorrow'), (7, 'Else')], default=1, verbose_name='Статус задачи'),
        ),
    ]
