# Generated by Django 4.2.7 on 2023-11-08 13:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPointModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес точки')),
                ('agent_point_date', models.CharField(choices=[('long_ago', 'Long Time'), ('yesterday', 'Yesterday')], max_length=25, verbose_name='Дата подключения точки')),
                ('materials', models.BooleanField(verbose_name='Материалы доставлены')),
                ('last_card_given', models.DateField(null=True, verbose_name='Дата последней выдачи карты')),
                ('num_given_cards', models.SmallIntegerField(verbose_name='Выданные карты')),
                ('approved_requests', models.SmallIntegerField(verbose_name='Одобренные заявки')),
                ('last_deliver', models.DateField(verbose_name='Последняя доставка материала')),
                ('last_teaching', models.DateField(verbose_name='Последнее проведение обуччения')),
                ('last_stimulation', models.DateField(verbose_name='Последняя стимуляция выдач')),
            ],
            options={
                'verbose_name': 'Агентские точки',
                'verbose_name_plural': 'Агентские точки',
                'db_table': 'AgentPoint',
            },
        ),
        migrations.CreateModel(
            name='TaskTypeModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Название типа задач')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], max_length=30, verbose_name='Приоритет задачи')),
                ('work_time', models.PositiveSmallIntegerField(verbose_name='Время выполнения')),
                ('condition_1', models.CharField(max_length=256, verbose_name='Условие 1')),
                ('condition_2', models.CharField(max_length=256, verbose_name='Условие 2')),
                ('grade', models.PositiveSmallIntegerField(choices=[(1, 'Junior'), (2, 'Middle'), (3, 'Senior')], verbose_name='Нужный грейд')),
            ],
            options={
                'verbose_name': 'Тип задач',
                'verbose_name_plural': 'Тип задач',
                'db_table': 'TaskType',
            },
        ),
    ]
