# Generated by Django 4.2.7 on 2023-11-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentpointmodel',
            name='agent_point_date',
            field=models.CharField(choices=[('давно', 'Long Time'), ('вчера', 'Yesterday')], max_length=25, verbose_name='Дата подключения точки'),
        ),
    ]
