# Generated by Django 4.2.7 on 2023-11-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktypemodel',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], verbose_name='Приоритет задачи'),
        ),
    ]
